### ISSUE TITLE
Code a Splash screen 

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#16]
Create a Splash Screen with a delay of 3 seconds which will just have the logo given in the figma file of the design folder

**Comment by RibhavBansal** [comment]
claim

**Comment by poga0204** [comment]
@RibhavBansal It's a girls only repo so you cannot claim it.

**Comment by anshgeez31** [comment]
claim

**Comment by poga0204** [comment]
@anshgeez31 it's a girls only repo. So this issue cannot be assigned to you.

**Comment by anshgeez31** [comment]
Oh Okk.

**Comment by bhumika-kalaru** [comment]
claim

**Comment by poga0204** [comment]
Assigned to @bhumika-kalaru
