### ISSUE TITLE
Create register page

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#21]
Code the register page by imitating the UI given in design folder (login_sign_up_ui) as close as possible

### **Note:**
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders
- Make the screens responsive by using MediaQuerry
- No need to add any functionality just mimic the UI

**Comment by bhumika-kalaru** [comment]
claim

**Comment by Prakriti-19** [comment]
@bhumika-kalaru you can only work on one issue at a time, until your previous pr gets merged this can't be assigned

**Comment by anjalii14** [comment]
claim

**Comment by BINGABABA** [comment]
claim

**Comment by anjalii14** [comment]
claim

**Comment by Prakriti-19** [comment]
Assigned to @BINGABABA 
All the Best!

**Comment by poga0204** [comment]
@BINGABABA updates?

**Comment by anjalii14** [comment]
claim

**Comment by poga0204** [comment]
Assigned to @anjalii14 and unassigned @BINGABABA
