### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#22]
Code the  Login Page by imitating the UI given in design folder (login_sign_up_ui) as close as possible

### **Note:**
- Deadline for the task is 21st Dec, 11:59 pm
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders
- Make the screens responsive by using MediaQuerry
- No need to add any functionality just mimic the UI

**Comment by bhumika-kalaru** [comment]
claim

**Comment by Prakriti-19** [comment]
Assigned issue to @bhumika-kalaru
