### ISSUE TITLE
It's Time To Animate

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#25]
Use your imagination and come up with a good animation for our Splash Screen

### **Note**
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders
- You can use any animation but try to keep it minimalistic

**Comment by anjalii14** [comment]
claim

**Comment by Prakriti-19** [comment]
Assigned to @anjalii14 
All the Best!
