### ISSUE TITLE
Add Authentication via email password

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#31]
With firebase already integrated in the project allow your users to register in your app by adding authentication using email and password in firebase

### **Note**

- In case you need access to backend share your email
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders
- Make a new dart file for each task and name it accordingly
- User should be registered by clicking on Register button of the SignUp page

**Comment by bhumika-kalaru** [comment]
claim

**Comment by Koshal7** [comment]
claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by abhinavs1920** [comment]
claim , please let me do this

**Comment by poga0204** [comment]
Assigned to @Koshal7 
All the Best!

**Comment by poga0204** [comment]
@Koshal7 updates?

**Comment by anjalii14** [comment]
claim

**Comment by abhinavs1920** [comment]
Claim

**Comment by Prakriti-19** [comment]
Assigned to @anjalii14 and Unassigned @Koshal7 
All the Best!!

**Comment by anjalii14** [comment]
what's the deadline?
