### ISSUE TITLE
Add a Check On The TextFields

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#32]
Add a condition such that the user can't proceed from register or login page without filling in all the details. If so an error message in red is displayed on the screen

### **Note**
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders

**Comment by bhumika-kalaru** [comment]
claim

**Comment by Koshal7** [comment]
claim

**Comment by abhinavs1920** [comment]
claim

**Comment by poga0204** [comment]
Assigned to @abhinavs1920 
All the Best!

**Comment by abhinavs1920** [comment]
Thank you for your response . Will complete the task as soon as possible.
