### ISSUE TITLE
Adding Navigation

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#33]
1. Convert text at the bottom of login and register pages ("Already have an account **Sign in**", "Don't have an account **Sign Up**") to textbutton and add navigation through it between the pages.
2. Also add an imagebutton of google above "Sign up with google" text

### **Note**
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders

**Comment by bhumika-kalaru** [comment]
claim

**Comment by Koshal7** [comment]
claim

**Comment by abhinavs1920** [comment]
claim

**Comment by poga0204** [comment]
assigned to @bhumika-kalaru
