### ISSUE TITLE
Create Donation Page

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#38]
Code the donation page by imitating the UI given in design folder (UI for donation page folder) as close as possible

### **Note:**
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders
- Make the screens responsive by using MediaQuerry
- No need to add any functionality just mimic the UI

**Comment by bhumika-kalaru** [comment]
Claim

**Comment by abhinavs1920** [comment]
Claim

**Comment by poga0204** [comment]
assigned to @bhumika-kalaru
