### ISSUE TITLE
Store the data

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#45]
Store all the details of the food as a document in firebase with user id of that donor also as a field as shown in the ss:
![2022-12-30](https://user-images.githubusercontent.com/111135506/210060501-5b1a6632-96c3-4b5e-b920-f4d5d8a189a8.png)

### **Note**
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders
- In case you need access to backend share your email

**Comment by bhumika-kalaru** [comment]
claim

**Comment by poga0204** [comment]
Assigned to @bhumika-kalaru
