### ISSUE TITLE
Validate the email

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#48]
Only valid email should be able to register in the app. Verify the email through which user is registering in the app either through OTP or online mail verification.

### **Note**
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders
- In case you need access to backend share your email

**Comment by bhumika-kalaru** [comment]
claim

**Comment by poga0204** [comment]
Assigned to @bhumika-kalaru. All the best!
