### ISSUE TITLE
Login via email password

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#49]
Once the user has registered, they should be able to login every time in your app by using email and password

### **Note**

- In case you need access to backend share your email
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders
- Make a new dart file for each task and name it accordingly
- User should be logged in by clicking on Login button of the SignIn page

**Comment by Shubhankit-Pandey** [comment]
Claim

**Comment by Prakriti-19** [comment]
Assigned to @Shubhankit-Pandey

**Comment by poga0204** [comment]
@Shubhankit-Pandey updates?

**Comment by Shubhankit-Pandey** [comment]
still working on it.

**Comment by poga0204** [comment]
okay

**Comment by Prakriti-19** [comment]
Issue open for reclaiming

**Comment by bhumika-kalaru** [comment]
Claim

**Comment by poga0204** [comment]
Assigned to @bhumika-kalaru
