### ISSUE TITLE
Change the UI

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#54]
Change the UI of homepage by cloning the one given in design folder(food inventory.txt)

**Comment by bhumika-kalaru** [comment]
Claim

**Comment by Prakriti-19** [comment]
@bhumika-kalaru only one issue at a time can be assigned

**Comment by bhumika-kalaru** [comment]
claim

**Comment by Prakriti-19** [comment]
Assigned to @bhumika-kalaru
