### ISSUE TITLE
Let's Filter Out

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#56]
Create a simple button on home page such that on clicking it we filter out and display only those food items that can serve more than 50 people

### **Note**
- In case you need access to backend share your email
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders
- Make a new dart file for each task and name it accordingly

**Comment by bhumika-kalaru** [comment]
claim

**Comment by Prakriti-19** [comment]
Assigned to @bhumika-kalaru
