### ISSUE TITLE
Need a Drawer

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#57]
Create a drawer on homescreen displaying- profile, search, filter and logout option. You can take reference from the image below:
![2023-01-07](https://user-images.githubusercontent.com/111135506/211162076-ec565661-c791-490d-ab77-71e332a61aca.png)

### **Note**
- No need to add any functionality
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders
- Make a new dart file for each task and name it accordingly

**Comment by bhumika-kalaru** [comment]
claim

**Comment by Prakriti-19** [comment]
Assigned to @bhumika-kalaru
