### ISSUE TITLE
Add Menu

### ISSUE THREAD

**Issue by Prakriti-19** [opencodeiiita/HandsForHunger#60]
Add a drop down menu on people filter button for ranges(<10, 11-20,20-50,50-100,>100) and add functionality to each button and filter the data depending on veg and non-veg:

### **Note**
- You are not allowed to make changes in any of the files except for pubsec.yaml and lib folders
- Make a new dart file for each task and name it accordingly

**Comment by SichangiFelix** [comment]
I would like to work on this.

**Comment by poga0204** [comment]
@SichangiFelix you would have to then claim it.
Just write claim and then we will assign you.

**Comment by bhumika-kalaru** [comment]
claim

**Comment by poga0204** [comment]
Assigned to @bhumika-kalaru
