### ISSUE TITLE
Design a logo for the app

### ISSUE THREAD

**Issue by poga0204** [opencodeiiita/HandsForHunger#7]
Design a logo which best fits the theme and concept of this app.

**Guidelines**

- Make sure you follow the given template in the .github folder before making the pull request.

- For submitting PR, you have to make a .txt file containing your github username and figma link and add it into the designs/logo folder.

- The deadline for the submission of this issue is **_18th December,11.59 P.M_**

**Note**

- The final decision will be taken by mentors.
- As it is an _**open to all**_ issue, therefore, no need to claim.

**Comment by anshgeez31** [comment]
claim

**Comment by BINGABABA** [comment]
claim

**Comment by Prakriti-19** [comment]
@BINGABABA  It's an 'open for all' issue. You don't need to claim it.
