### ISSUE TITLE
Design a welcome screen

### ISSUE THREAD

**Issue by poga0204** [opencodeiiita/HandsForHunger#8]
Design a welcome screen for the app which asks users whether they are food donors or NGO before navigating them to the signup page

**Things to consider before making a design :**

- The page will have a welcome message and ask donors to choose if they are food donors or NGO.

- Designs need to be minimal and intuitive.

**Submission Guidelines :**

- For submitting PR, you have to make a .txt file containing your github username and figma link and add it into the designs/logo folder.
- The top 2 designs will be rewarded with points.
- The deadline for the submission of this issue is **_18th December,11.59 P.M_**

- Make sure the visibility of the Figma File is public.

Note that the issue is **_Open for All_**. There is no need to claim this issue. You can directly submit a PR

**Comment by anjalii14** [comment]
claim

**Comment by BINGABABA** [comment]
claim

**Comment by Prakriti-19** [comment]
@anjalii14  @BINGABABA It's an 'open for all' issue. You don't need to claim it. Just submit the PR before the deadline
