### ISSUE TITLE
Design SignIn/SignUp page

### ISSUE THREAD

**Issue by poga0204** [opencodeiiita/HandsForHunger#9]
**Things to consider before making the design :**

- The page must have input fields for email and password and sign in through google option.

- Designs need to be minimal and intuitive.

**Submission Guidelines :**
For submitting PR, you have to make a .txt file containing your github username and figma link and add it into the designs/logo folder.

- The deadline for the submission of this issue is **_19th December,10.00 A.M_**

- The **top 2 designs** will be rewarded with points.

- Make sure the visibility of the Figma File is public.

- The final decision will be taken by **mentors.**

- Note that the issue is **_Open for All_**. There is no need to claim this issue. You can directly submit a PR

**Comment by anjalii14** [comment]
claim

**Comment by poga0204** [comment]
@anjalii14 It's an open for all issue. You don't need to claim it.

**Comment by vedant-z** [comment]
@poga0204 One needs to make only design in figma, no need of code right?

**Comment by poga0204** [comment]
@vedant-z yes this a design only issue, so no code. But this is a **girls only repo**. So keep it in mind.
